# spring:
#    datasource:
     url: jdbc:mysql://localhost:3306/expense?useSSL=false
#      username: root
#      password: dummy


#     #  JPA Settings

#     jpa.hibernate.ddl_auto: create / update